name: Goreleaser (Dry Run)

on:
  push:
    branches: [ main ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - Dockerfile*
      - .dockerignore
      - ui/**
      - cmd/**
      - pkg/**
      - internal/**
      - gen/**
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - Dockerfile*
      - .dockerignore
      - ui/**
      - cmd/**
      - pkg/**
      - internal/**
      - gen/**

permissions:
  contents: write

jobs:
  goreleaser:
    name: Goreleaser Dry Run
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true

      - name: Set up environment
        run: |
          ./env.sh
          ./env-proto.sh
          ./env-jsonnet.sh

      - name: Build UI
        run: make ui/build

      - name: Format
        run: make format && git diff --exit-code

      - name: Validate
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Set Tag
        run: |
          echo "goreleaser_current_tag=`git describe --match 'v*' --tags`" >> $GITHUB_ENV

      - name: Dry Run
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-validate --skip-publish
        env:
          GORELEASER_CURRENT_TAG: "${{ env.goreleaser_current_tag }}"
